# Changes here will be overwritten by Copier
_commit: 2.0.0
_src_path: gh:markusritschel/cookiecutter-pyproject
command_line_interface: Click
docs_engine: Sphinx
github_user: markusritschel
is_research_project: false
package_name: oceanpack
project_description: This repository contains routines for the evaluation of data from the OceanPack™ AUMS (Autonomous Underwater Measuring System) by SubCtech®.
project_license: MIT license
project_name: Oceanpack
project_slug: oceanpack
project_version: 0.1.0
user_email: git@markusritschel.de
user_name: Markus Ritschel

